# Generated by Django 4.1.6 on 2023-02-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='username',
        ),
    ]
