# Generated by Django 4.1.6 on 2023-02-12 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_rename_user_conversation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='username_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='phrase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
