# Generated by Django 4.1.6 on 2023-02-12 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_conversation_username_id_alter_conversation_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='username_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
